### ISSUE TITLE
exception empty excel

### ISSUE THREAD

**Issue by yunusdursunturan** [btargac/excel-parser-processor#15]
<img width="801" alt="screen shot 2018-03-20 at 10 46 20" src="https://user-images.githubusercontent.com/12999491/37641781-0fc54864-2c2c-11e8-8171-6ae293f987c0.png">

gives an error in an empty excel!

<img width="798" alt="screen shot 2018-03-20 at 10 46 33" src="https://user-images.githubusercontent.com/12999491/37641789-18674490-2c2c-11e8-8def-354c72b58211.png">

can't application restart

**Comment by btargac** [comment]
this error is fixed and merged to master branch, with the next release 1.0.5 empty excel files will be handled. @yunusdursunturan

**Comment by yunusdursunturan** [comment]
<img width="792" alt="screen shot 2018-03-26 at 17 04 41" src="https://user-images.githubusercontent.com/12999491/37911103-d616946a-3117-11e8-8374-6441010639fc.png">
?

**Comment by btargac** [comment]
seems like is-url module is throwing an exception. I'll check that with a different excel file.

**Comment by btargac** [comment]
<img width="800" alt="screen shot 2018-03-28 at 00 50 16" src="https://user-images.githubusercontent.com/5160933/37996973-33f168fc-3222-11e8-9b16-eedfb17274b4.png">
snapshot of the app when an excel file has no item to download, after is-url module is updated.

**Comment by btargac** [comment]
@yunusdursunturan this problem is fixed with 1.0.5 if any similar issue happens we can create a new issue
