### ISSUE TITLE
a javascript error occured in the main process

### ISSUE THREAD

**Issue by Susanthakuri92** [btargac/excel-parser-processor#53]
I am getting this problem in some photos.anyone knows ?
![image](https://user-images.githubusercontent.com/80942813/111740151-58c52680-88ac-11eb-9580-12f5c19681be.png)

**Comment by btargac** [comment]
Hi @Susanthakuri92 can you add the excel file that you are trying to process ?

**Comment by btargac** [comment]
I see a * character on the file name that the program is trying to save on file system, I should check if this file name is safe for windows, by the way you are using windows as I understood from file path is that right ?

**Comment by Susanthakuri92** [comment]
> Hi @Susanthakuri92 can you add the excel file that you are trying to process ?

[images.xlsx](https://github.com/btargac/excel-parser-processor/files/6169412/images.xlsx)

**Comment by Susanthakuri92** [comment]
> I see a * character on the file name that the program is trying to save on file system, I should check if this file name is safe for windows, by the way you are using windows as I understood from file path is that right ?

so is that symbol a problem?

**Comment by Susanthakuri92** [comment]
> I see a * character on the file name that the program is trying to save on file system, I should check if this file name is safe for windows, by the way you are using windows as I understood from file path is that right ?

yes I am using windows

**Comment by btargac** [comment]
I checked from windows documentation, and it states that asterisk is not allowed
https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file#naming-conventions

**Comment by btargac** [comment]
any updates on this case ? Could you try removing the one with asterisk @Susanthakuri92 ?

**Comment by btargac** [comment]
You can use the B column to rename the file when saving

for example;

if resource is `https://www.sample.com/sam*ple.jpg` then you can replace automatically with the B column by just setting it to something like `sample` then it will be saved on your file system as `sample.jpg`

you can check the sample table with optional fields from [here](https://github.com/btargac/excel-parser-processor#sample-excel-file-structure)

**Comment by btargac** [comment]
Since no development is required to solve this problem, I am closing this issue, if further problems arise we can re open this accordingly

**Comment by Susanthakuri92** [comment]
Hlw sir, I am not being able to download images from dropbox link.It gets
download but after i open image doesnt supports
here is a link https://www.dropbox.com/s/w11dpu6t95jsv0z/MM-1000C_1.jpg
<https://www.dropbox.com/s/w11dpu6t95jsv0z/MM-1000C_1.jpg?dl=0>

**Comment by btargac** [comment]
Hi @Susanthakuri92 ,

I checked your resource form your deopbox url but dropbox servers return a HTML response not the image itself. I mean a png, jpg or a gif is required to you not the html for example if you request directly to the address below;
 https://uc6faff32e58737c0bea8e89bb83.previews.dropboxusercontent.com/p/thumb/ABL6X0KzSSQT2jVC2cUj-1_qBp-2uKr5gyaAQvJj0-E49ldMUOnwkidUfc2XZwMByFZzH4uDJl0DOHe_yS3c8PsHlKb-0ZjWvAp_QM99MQw_EFeb0vQCO306_uES8CwhzFD48BrGDFsJbfG-4V6e-Hw2XJck2NkwZ5KJMubMmyciV25QRm6CBYzS4qrBCkVHKlcmm9qepiSbUNYYd2qSNLz3vcOrf2yZfr1OsyclGy6vv4xz2yXo3pBc_08-spP17Nq7qre8Ga7DLhEzKWmbq-est9qdsDDEpE0RID4iYjwAaBOeVyIEFMPUUjaaKe3JglvGbc_jx7PglymLvQPDYnkO68TlC0GRDVawlywxMXQYZm2WQbZ6BAV5ssZG227dKikFCtDgpPEDemL1iJyYBi8u/p.jpeg?fv_content=true&size_mode=5 you'll get the original image but with your url it's not possible

**Comment by Susanthakuri92** [comment]
Thank you for the clarification.

**Comment by Susanthakuri92** [comment]
Hlw Sir I am new to Linux and I want to ask how Can I install the excel
Parser processor app in Linux.

**Comment by btargac** [comment]
Hi @Susanthakuri92 , I am not a linux user either but I think you should download the AppImage file from [here](https://github.com/btargac/excel-parser-processor/releases/download/v1.3.0/Excel-Parser-Processor-1.3.0.AppImage).

and after your download is completed just open a terminal/cli etc. and below command can help you with that.

```bash
# Make it executable
# don't forget to go to the directory that has the downloaded file
chmod a+x Excel-Parser-Processor*.AppImage
# and run!
./Excel-Parser-Processor*.AppImage
```

**Comment by Susanthakuri92** [comment]
Thanks, I'll check it out.
