### ISSUE TITLE
Workaround for sites banning ip?

### ISSUE THREAD

**Issue by codearm2** [btargac/excel-parser-processor#67]
Very nice tool, tested on some sites and it works wonderfully

However, one of my target site banned me immediately after 80 requests

Any workaround besides VPN, proxies etc?

Can we set the scrapping speed? It's ok for me to scrap slower

**Comment by btargac** [comment]
Hello @codearm2,

Thanks for your feedback. 

Actually I did not encounter such a domain while testing it, but as you mentioned there can be cases like you came across.This app should be fine if you switch to a VPN or proxy but currently it doesn't have such a delayed download mode. But I can add that feature with an optional toggle on the UI. If you are familiar you can also add that flexibility via some javascript changes on your machine. By adding a setTimeout to the stack

**Comment by codearm2** [comment]
> Hello @codearm2,
> 
> Thanks for your feedback.
> 
> Actually I did not encounter such a domain while testing it, but as you mentioned there can be cases like you came across.This app should be fine if you switch to a VPN or proxy but currently it doesn't have such a delayed download mode. But I can add that feature with an optional toggle on the UI. If you are familiar you can also add that flexibility via some javascript changes on your machine. By adding a setTimeout to the stack

Hi
I already added setTimeout and add toggle button, it works well now 

Thanks for the reply
