### ISSUE TITLE
Nothing happens after file select

### ISSUE THREAD

**Issue by jontesamuelsson** [btargac/excel-parser-processor#75]
I downloaded the windows version 1.3.0. But when I have selected the xls nothing more happens. Tested both drag&drop and using browse. 

Expected to get to choose a folder for download. Not showing. No images downloads.

What can be the problem? my column A is Url, column B is filename.

**Comment by btargac** [comment]
Hi @jontesamuelsson , if the file doesn't have an extension it can be the problem but if that's not the case can you share the file or a small part of it to check if I could reproduce on my windows machine ? And which version of windows are you using ?

**Comment by jontesamuelsson** [comment]
Hello!

Thanks for reply

I’m running Win 10 Pro (20H2, version 19042.1526)
I attached a file here. Tried with or without extension in filename-column.

Best regards
Jonatan

**Comment by btargac** [comment]
Hi Jonatan , I can not see the attached file on github ? 

Could it be that you replied with email client and attached the file there ?

**Comment by jontesamuelsson** [comment]
Oh sorry, that is what happened. New try here.
[image-test.xls](https://github.com/btargac/excel-parser-processor/files/8047809/image-test.xls)

**Comment by btargac** [comment]
@jontesamuelsson hi, your issue is related to the xls file type, probably it was created or modified by an old version of Excel and that's why while filtering the file if it was an actual excel or not it was skipped. The next release 1.3.1 will not have this issue, today I assume I'll publish with some extra updates. Will let you know when it's ready 👍🏼

**Comment by btargac** [comment]
you can download the latest release from [here](https://github.com/btargac/excel-parser-processor/releases/tag/v1.3.1).

**Comment by jontesamuelsson** [comment]
Perfect :-)
Now it's works with xls created from OpenOffice.
Nice work!
